// <auto-generated />
using System;
using BookingSystem.Persistence.DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BookingSystem.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.19");

            modelBuilder.Entity("BookingSystem.Persistence.Entities.Booking", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BookedQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<long>("ResourceId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Uid")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ResourceId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("BookingSystem.Persistence.Entities.Resource", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("Uid")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Resources");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Resource 1",
                            Quantity = 100,
                            Uid = new Guid("08bb3dde-09eb-453e-a2f2-d34183c0c5bb")
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Resource 2",
                            Quantity = 200,
                            Uid = new Guid("18bb3dde-09eb-453e-a2f2-d34183c0c5bb")
                        },
                        new
                        {
                            Id = 3L,
                            Name = "Resource 3",
                            Quantity = 300,
                            Uid = new Guid("28bb3dde-09eb-453e-a2f2-d34183c0c5bb")
                        },
                        new
                        {
                            Id = 4L,
                            Name = "Resource 4",
                            Quantity = 400,
                            Uid = new Guid("38bb3dde-09eb-453e-a2f2-d34183c0c5bb")
                        },
                        new
                        {
                            Id = 5L,
                            Name = "Resource 5",
                            Quantity = 500,
                            Uid = new Guid("48bb3dde-09eb-453e-a2f2-d34183c0c5bb")
                        },
                        new
                        {
                            Id = 6L,
                            Name = "Resource 6",
                            Quantity = 600,
                            Uid = new Guid("58bb3dde-09eb-453e-a2f2-d34183c0c5bb")
                        },
                        new
                        {
                            Id = 7L,
                            Name = "Resource 7",
                            Quantity = 700,
                            Uid = new Guid("68bb3dde-09eb-453e-a2f2-d34183c0c5bb")
                        },
                        new
                        {
                            Id = 8L,
                            Name = "Resource 8",
                            Quantity = 800,
                            Uid = new Guid("78bb3dde-09eb-453e-a2f2-d34183c0c5bb")
                        },
                        new
                        {
                            Id = 9L,
                            Name = "Resource 9",
                            Quantity = 900,
                            Uid = new Guid("88bb3dde-09eb-453e-a2f2-d34183c0c5bb")
                        },
                        new
                        {
                            Id = 10L,
                            Name = "Resource 10",
                            Quantity = 1000,
                            Uid = new Guid("98bb3dde-09eb-453e-a2f2-d34183c0c5bb")
                        });
                });

            modelBuilder.Entity("BookingSystem.Persistence.Entities.Booking", b =>
                {
                    b.HasOne("BookingSystem.Persistence.Entities.Resource", "Resource")
                        .WithMany("Bookings")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
